---
- hosts: all
  become: true
  tasks:
    - name: Add repository for PHP versions (Ubuntu).
      apt_repository: repo='ppa:ondrej/php'
      when: ansible_distribution == "Ubuntu"
      register: php_ondrej_debian_repo
    - name: Update apt caches after repo is added (Debian).
      apt: update_cache=true
      when:
        - php_ondrej_debian_repo.changed
        - ansible_distribution == "Debian"
    - name: install lamp
      package: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2', 'mysql-server-8.0', 'python3-pymysql', 'php8.2', 'php8.2-mysql', 'libapache2-mod-php8.2','php8.2-curl', 'php8.2-gd', 'php8.2-mbstring', 'php8.2-xml', 'php8.2-xmlrpc', 'php8.2-soap', 'php8.2-intl', 'php8.2-zip' ]

    - name: enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify: restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
